=== LonelyTrouvere/OOP_lab2/bin/file.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="GunList">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Gun" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="model" type="xs:string"/>
              <xs:element name="handy" type="xs:boolean"/>
              <xs:element name="origin" type="xs:string"/>
              <xs:element name="material" type="xs:string"/>
              <xs:element name="ttc">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="range">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="CLOSE"/>
                          <xs:enumeration value="MID"/>
                          <xs:enumeration value="LONG"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="aimed" type="xs:int"/>
                    <xs:element name="clip" type="xs:int"/>
                    <xs:element name="scope" type="xs:boolean"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== LonelyTrouvere/OOP_lab2/src/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<GunList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="file.xsd">
    <Gun id="43264823">
        <model>MP-5</model>
        <handy>false</handy>
        <origin>Germany</origin>
        <material>Plastic</material>
        <ttc>
            <range>MID</range>
            <aimed>300</aimed>
            <clip>25</clip>
            <scope>false</scope>
        </ttc>
    </Gun>
    <Gun id="90943274">
        <model>FN F2000</model>
        <handy>false</handy>
        <origin>Belgium</origin>
        <material>Plastic</material>
        <ttc>
            <range>MID</range>
            <aimed>500</aimed>
            <clip>40</clip>
            <scope>true</scope>
        </ttc>
    </Gun>
</GunList>
